"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    "animal.py",
    "color.py",
    "enviroment.py",
    "role.py",
    "ui.py",
    "ItemInfo.json",
    ("", ["map", "texture"])]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
